// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/addnewdata/addnew.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/delete/[deleteid].tsx";
import * as $4 from "./routes/edit/[editId].tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DeleteForm.tsx";
import * as $$2 from "./islands/Editform.tsx";
import * as $$3 from "./islands/addform.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/addnewdata/addnew.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/delete/[deleteid].tsx": $3,
    "./routes/edit/[editId].tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DeleteForm.tsx": $$1,
    "./islands/Editform.tsx": $$2,
    "./islands/addform.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
